import { z } from "zod";
export declare const feedCategorySchema: z.ZodEnum<["ai", "web", "app", "backend", "security"]>;
export declare const severitySchema: z.ZodEnum<["critical", "high", "medium", "low", "unknown"]>;
export declare const alertSeveritySchema: z.ZodEnum<["critical", "high", "medium", "low", "info"]>;
export declare const exploitStatusSchema: z.ZodEnum<["known_exploited", "suspected", "none", "unknown"]>;
export declare const impactConfidenceSchema: z.ZodEnum<["exact", "likely", "no_match", "unknown"]>;
export declare const sourceTypeSchema: z.ZodEnum<["news", "security"]>;
export declare const sourceSchema: z.ZodObject<{
    id: z.ZodString;
    key: z.ZodString;
    name: z.ZodString;
    type: z.ZodEnum<["news", "security"]>;
    enabled: z.ZodBoolean;
    pollIntervalMinutes: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    id: string;
    key: string;
    name: string;
    type: "security" | "news";
    enabled: boolean;
    pollIntervalMinutes: number;
}, {
    id: string;
    key: string;
    name: string;
    type: "security" | "news";
    enabled: boolean;
    pollIntervalMinutes: number;
}>;
export declare const feedItemSchema: z.ZodObject<{
    id: z.ZodString;
    sourceId: z.ZodString;
    externalId: z.ZodString;
    title: z.ZodString;
    slug: z.ZodString;
    url: z.ZodString;
    sourceName: z.ZodString;
    author: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    publishedAt: z.ZodString;
    fetchedAt: z.ZodString;
    category: z.ZodEnum<["ai", "web", "app", "backend", "security"]>;
    tags: z.ZodArray<z.ZodString, "many">;
    summaryKo: z.ZodString;
    whyItMattersKo: z.ZodString;
    actionLabel: z.ZodEnum<["Read", "Watch", "Upgrade now"]>;
    importanceScore: z.ZodNumber;
    discussionScore: z.ZodNumber;
    freshnessScore: z.ZodNumber;
    finalScore: z.ZodNumber;
    canonicalUrl: z.ZodString;
    dedupeKey: z.ZodString;
    imageUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    rawPayload: z.ZodRecord<z.ZodString, z.ZodAny>;
}, "strip", z.ZodTypeAny, {
    id: string;
    sourceId: string;
    externalId: string;
    title: string;
    slug: string;
    url: string;
    sourceName: string;
    publishedAt: string;
    fetchedAt: string;
    category: "ai" | "web" | "app" | "backend" | "security";
    tags: string[];
    summaryKo: string;
    whyItMattersKo: string;
    actionLabel: "Read" | "Watch" | "Upgrade now";
    importanceScore: number;
    discussionScore: number;
    freshnessScore: number;
    finalScore: number;
    canonicalUrl: string;
    dedupeKey: string;
    rawPayload: Record<string, any>;
    author?: string | null | undefined;
    imageUrl?: string | null | undefined;
}, {
    id: string;
    sourceId: string;
    externalId: string;
    title: string;
    slug: string;
    url: string;
    sourceName: string;
    publishedAt: string;
    fetchedAt: string;
    category: "ai" | "web" | "app" | "backend" | "security";
    tags: string[];
    summaryKo: string;
    whyItMattersKo: string;
    actionLabel: "Read" | "Watch" | "Upgrade now";
    importanceScore: number;
    discussionScore: number;
    freshnessScore: number;
    finalScore: number;
    canonicalUrl: string;
    dedupeKey: string;
    rawPayload: Record<string, any>;
    author?: string | null | undefined;
    imageUrl?: string | null | undefined;
}>;
export declare const feedBriefingSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    keyPoints: z.ZodArray<z.ZodString, "many">;
}, "strip", z.ZodTypeAny, {
    title: string;
    summary: string;
    keyPoints: string[];
}, {
    title: string;
    summary: string;
    keyPoints: string[];
}>;
export declare const securityImpactBriefingSchema: z.ZodObject<{
    title: z.ZodString;
    intro: z.ZodString;
    sideEffects: z.ZodArray<z.ZodString, "many">;
    operationalRisk: z.ZodString;
}, "strip", z.ZodTypeAny, {
    title: string;
    intro: string;
    sideEffects: string[];
    operationalRisk: string;
}, {
    title: string;
    intro: string;
    sideEffects: string[];
    operationalRisk: string;
}>;
export declare const securityIncidentSchema: z.ZodObject<{
    id: z.ZodString;
    canonicalKey: z.ZodString;
    title: z.ZodString;
    summaryKo: z.ZodString;
    whyItMattersKo: z.ZodString;
    packageName: z.ZodString;
    ecosystem: z.ZodString;
    severity: z.ZodEnum<["critical", "high", "medium", "low", "unknown"]>;
    affectedVersionRanges: z.ZodArray<z.ZodString, "many">;
    fixedVersions: z.ZodArray<z.ZodString, "many">;
    aliases: z.ZodArray<z.ZodString, "many">;
    references: z.ZodArray<z.ZodString, "many">;
    exploitStatus: z.ZodEnum<["known_exploited", "suspected", "none", "unknown"]>;
    publishedAt: z.ZodString;
    modifiedAt: z.ZodString;
    sourcePriority: z.ZodNumber;
    actionRequired: z.ZodBoolean;
    recommendation: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    title: string;
    publishedAt: string;
    summaryKo: string;
    whyItMattersKo: string;
    canonicalKey: string;
    packageName: string;
    ecosystem: string;
    severity: "critical" | "high" | "medium" | "low" | "unknown";
    affectedVersionRanges: string[];
    fixedVersions: string[];
    aliases: string[];
    references: string[];
    exploitStatus: "unknown" | "known_exploited" | "suspected" | "none";
    modifiedAt: string;
    sourcePriority: number;
    actionRequired: boolean;
    recommendation: string;
}, {
    id: string;
    title: string;
    publishedAt: string;
    summaryKo: string;
    whyItMattersKo: string;
    canonicalKey: string;
    packageName: string;
    ecosystem: string;
    severity: "critical" | "high" | "medium" | "low" | "unknown";
    affectedVersionRanges: string[];
    fixedVersions: string[];
    aliases: string[];
    references: string[];
    exploitStatus: "unknown" | "known_exploited" | "suspected" | "none";
    modifiedAt: string;
    sourcePriority: number;
    actionRequired: boolean;
    recommendation: string;
}>;
export declare const watchlistItemSchema: z.ZodObject<{
    id: z.ZodString;
    packageName: z.ZodString;
    ecosystem: z.ZodString;
    currentVersion: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    isActive: z.ZodBoolean;
    impactConfidence: z.ZodOptional<z.ZodEnum<["exact", "likely", "no_match", "unknown"]>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    packageName: string;
    ecosystem: string;
    isActive: boolean;
    currentVersion?: string | null | undefined;
    impactConfidence?: "unknown" | "exact" | "likely" | "no_match" | undefined;
}, {
    id: string;
    packageName: string;
    ecosystem: string;
    isActive: boolean;
    currentVersion?: string | null | undefined;
    impactConfidence?: "unknown" | "exact" | "likely" | "no_match" | undefined;
}>;
export declare const userAlertSchema: z.ZodObject<{
    id: z.ZodString;
    type: z.ZodEnum<["security", "feed"]>;
    title: z.ZodString;
    body: z.ZodString;
    severity: z.ZodEnum<["critical", "high", "medium", "low", "info"]>;
    status: z.ZodEnum<["unread", "read", "archived"]>;
    createdAt: z.ZodString;
    readAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    type: "security" | "feed";
    status: "unread" | "read" | "archived";
    title: string;
    severity: "critical" | "high" | "medium" | "low" | "info";
    body: string;
    createdAt: string;
    readAt?: string | null | undefined;
}, {
    id: string;
    type: "security" | "feed";
    status: "unread" | "read" | "archived";
    title: string;
    severity: "critical" | "high" | "medium" | "low" | "info";
    body: string;
    createdAt: string;
    readAt?: string | null | undefined;
}>;
export declare const dashboardSummarySchema: z.ZodObject<{
    criticalIncidentCount: z.ZodNumber;
    watchedAtRiskCount: z.ZodNumber;
    todayFeedCount: z.ZodNumber;
    topPriorityLabel: z.ZodString;
}, "strip", z.ZodTypeAny, {
    criticalIncidentCount: number;
    watchedAtRiskCount: number;
    todayFeedCount: number;
    topPriorityLabel: string;
}, {
    criticalIncidentCount: number;
    watchedAtRiskCount: number;
    todayFeedCount: number;
    topPriorityLabel: string;
}>;
export declare const feedQuerySchema: z.ZodObject<{
    category: z.ZodOptional<z.ZodEnum<["ai", "web", "app", "backend", "security"]>>;
    tag: z.ZodOptional<z.ZodString>;
    sort: z.ZodOptional<z.ZodEnum<["latest", "important", "discussed"]>>;
    cursor: z.ZodOptional<z.ZodString>;
    limit: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    sort?: "latest" | "important" | "discussed" | undefined;
    category?: "ai" | "web" | "app" | "backend" | "security" | undefined;
    tag?: string | undefined;
    cursor?: string | undefined;
    limit?: number | undefined;
}, {
    sort?: "latest" | "important" | "discussed" | undefined;
    category?: "ai" | "web" | "app" | "backend" | "security" | undefined;
    tag?: string | undefined;
    cursor?: string | undefined;
    limit?: number | undefined;
}>;
export declare const incidentQuerySchema: z.ZodObject<{
    severity: z.ZodOptional<z.ZodEnum<["critical", "high", "medium", "low", "unknown"]>>;
    ecosystem: z.ZodOptional<z.ZodString>;
    package: z.ZodOptional<z.ZodString>;
    onlyWatched: z.ZodOptional<z.ZodBoolean>;
    cursor: z.ZodOptional<z.ZodString>;
    limit: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    ecosystem?: string | undefined;
    severity?: "critical" | "high" | "medium" | "low" | "unknown" | undefined;
    cursor?: string | undefined;
    limit?: number | undefined;
    package?: string | undefined;
    onlyWatched?: boolean | undefined;
}, {
    ecosystem?: string | undefined;
    severity?: "critical" | "high" | "medium" | "low" | "unknown" | undefined;
    cursor?: string | undefined;
    limit?: number | undefined;
    package?: string | undefined;
    onlyWatched?: boolean | undefined;
}>;
export declare const normalizedFeedStagingSchema: z.ZodObject<{
    sourceKey: z.ZodString;
    externalId: z.ZodString;
    title: z.ZodString;
    url: z.ZodString;
    author: z.ZodOptional<z.ZodString>;
    publishedAt: z.ZodString;
    category: z.ZodEnum<["ai", "web", "app", "backend", "security"]>;
    tags: z.ZodArray<z.ZodString, "many">;
    rawPayload: z.ZodRecord<z.ZodString, z.ZodAny>;
}, "strip", z.ZodTypeAny, {
    externalId: string;
    title: string;
    url: string;
    publishedAt: string;
    category: "ai" | "web" | "app" | "backend" | "security";
    tags: string[];
    rawPayload: Record<string, any>;
    sourceKey: string;
    author?: string | undefined;
}, {
    externalId: string;
    title: string;
    url: string;
    publishedAt: string;
    category: "ai" | "web" | "app" | "backend" | "security";
    tags: string[];
    rawPayload: Record<string, any>;
    sourceKey: string;
    author?: string | undefined;
}>;
export declare const normalizedSecurityStagingSchema: z.ZodObject<{
    sourceKey: z.ZodString;
    packageName: z.ZodString;
    ecosystem: z.ZodString;
    title: z.ZodString;
    aliases: z.ZodArray<z.ZodString, "many">;
    affectedVersionRanges: z.ZodArray<z.ZodString, "many">;
    fixedVersions: z.ZodArray<z.ZodString, "many">;
    references: z.ZodArray<z.ZodString, "many">;
    severity: z.ZodEnum<["critical", "high", "medium", "low", "unknown"]>;
    exploitStatus: z.ZodEnum<["known_exploited", "suspected", "none", "unknown"]>;
    publishedAt: z.ZodString;
    modifiedAt: z.ZodString;
    rawPayload: z.ZodRecord<z.ZodString, z.ZodAny>;
}, "strip", z.ZodTypeAny, {
    title: string;
    publishedAt: string;
    rawPayload: Record<string, any>;
    packageName: string;
    ecosystem: string;
    severity: "critical" | "high" | "medium" | "low" | "unknown";
    affectedVersionRanges: string[];
    fixedVersions: string[];
    aliases: string[];
    references: string[];
    exploitStatus: "unknown" | "known_exploited" | "suspected" | "none";
    modifiedAt: string;
    sourceKey: string;
}, {
    title: string;
    publishedAt: string;
    rawPayload: Record<string, any>;
    packageName: string;
    ecosystem: string;
    severity: "critical" | "high" | "medium" | "low" | "unknown";
    affectedVersionRanges: string[];
    fixedVersions: string[];
    aliases: string[];
    references: string[];
    exploitStatus: "unknown" | "known_exploited" | "suspected" | "none";
    modifiedAt: string;
    sourceKey: string;
}>;
export type FeedCategory = z.infer<typeof feedCategorySchema>;
export type Severity = z.infer<typeof severitySchema>;
export type AlertSeverity = z.infer<typeof alertSeveritySchema>;
export type ImpactConfidence = z.infer<typeof impactConfidenceSchema>;
export type FeedItem = z.infer<typeof feedItemSchema>;
export type FeedBriefing = z.infer<typeof feedBriefingSchema>;
export type SecurityImpactBriefing = z.infer<typeof securityImpactBriefingSchema>;
export type SecurityIncident = z.infer<typeof securityIncidentSchema>;
export type WatchlistItem = z.infer<typeof watchlistItemSchema>;
export type UserAlert = z.infer<typeof userAlertSchema>;
export type DashboardSummary = z.infer<typeof dashboardSummarySchema>;
export type NormalizedFeedStaging = z.infer<typeof normalizedFeedStagingSchema>;
export type NormalizedSecurityStaging = z.infer<typeof normalizedSecurityStagingSchema>;
